### ISSUE TITLE
New Graphic BMP's.

### ISSUE THREAD

**Issue by ImReallyShiny** [ahezard/NitroHax#10]
This is an enhancement Issue.

I was bored and got these made in 30 ish mins.
I dont know if they work - But if they do, They should look AWESOME!

These are Minimal, Flat style BMP's.
It's up to you if you want to use them or not.

[BMP's.zip](https://github.com/ahezard/NitroHax/files/462705/BMP.s.zip)
(Bit unsure about the bgtop.bmp, Might re-do it a bit better later)

EDIT: The textbox.bmp was pure white, Which is how it was meant to be, But I just realized its too much work to render black text (Having to edit font.bmp and editing the code a ton, Too much work lol)
So heres a re-do of it.
[textbox.zip](https://github.com/ahezard/NitroHax/files/462722/textbox.zip)

**Comment by ApacheThunder** [comment]
Yeah that looks good. Ahezard seems to like the old UI for some odd reason. You have to convince him. I'm already on board with a UI change. :P

**Comment by ImReallyShiny** [comment]
@ahezard Up to you than I guess. :)
@ApacheThunder I have no idea if you are using DevkitPro or whatever, So can you compile it with my bmp's so I can use it? :P No need to make it as a release as of yet, Just upload it through here.

**Comment by ApacheThunder** [comment]
Yes this project uses devkitpro with the exception that it uses Ahezard's fork of libnds. Simply download his fork, compile it, and replace stock libnds with his.

**Comment by ahezard** [comment]
I have tried to compile with these bitmaps and the display is completely corrupted. I have no idea why. If you can fix the display I will integrate them.

**Comment by ahezard** [comment]
Apache fixed the issue, it was a bit depth problem : it should be 4bpp (16 colors) and not 24 bpp. In the future you can use an image conversion program like xnconvert or irfanview to fix this. This will be included in the next release. Thanks for you work Shiny!

**Comment by ImReallyShiny** [comment]
No problem! My bad about the color depth I chose 24bpp as its generally better quality sucks that you needa use 16bit

**Comment by ImReallyShiny** [comment]
Damn the Graphics in the new release looks amazing :P Forgot to make a new icon doe (And im unsure what encoding type its meant to be in, So ill make one in PNG and upload it here soon)

**Comment by ApacheThunder** [comment]
The compiler expects 256 color BMP I believe. Make sure the first color entry in the palette is not used or is your alpha, because a lot of image editors by default use the first color entry in the palette for black I believe. Either fix the palette or not use that specific color for important bits of your icon you don't want to appear white in the home menu.

Also the bottom screen is kinda plain right now. Maybe have a similar background for it as the top screen? Maybe just something more subtle. New scroll bar graphics would be nice too. ;)

**Comment by ImReallyShiny** [comment]
The Icon.bmp is really restrictive - The Pink/Purple color im assuming is basically the Alpha right? But its it necessary to have alpha in it?
Due to its sizing I cant seem to make an icon thats 100% crisp, But this looks pretty good:
[icon.zip](https://github.com/ahezard/NitroHax/files/468638/icon.zip)

Its set to "Windows/16bit" so it should work :+1: 
-
Yes the bottom screen was intentionally plain, I made it the exact same color as the very top right pixel of the Top Screen so that it blends in. The only place I see necessary to add anything fancy to is the sides of the Start Game button. A smoke looking effect might look cool there, The only thing is I cant really tell what the exact pixels of that area is.

Since my only way to screenshot is through NTRBoot and NTRBoot gets closed when you open DSiWare, I have no way to screenshot it and use that as a reference point.

All I can do atm is guess where the button is relative to the Background.

And as for the scroll bar, I didnt have plans on making BMP's for it due to it already fitting in really nice, But the Top ^ and Bottom V bits could look better if they were re-done Square with a Outline No Fill Triangle and then the middle bit with a slightly darker color might look good.

Ill work on that too

**Comment by ImReallyShiny** [comment]
http://i.imgur.com/nwKBEsK.png
This is a pretty good mockup I got going, The sizes used seems to be spot on.
The smoke on the bottom is subtle but looks pretty good.

**Comment by ImReallyShiny** [comment]
[bgsub.zip](https://github.com/ahezard/NitroHax/files/468654/bgsub.zip)

**Comment by ImReallyShiny** [comment]
[scrollbar.zip](https://github.com/ahezard/NitroHax/files/468670/scrollbar.zip)
It looks pretty good!
Just worried about the compression when its actually being rendered.

**Comment by ImReallyShiny** [comment]
Is it possible for you or Ahezard to try and move the "Cheat list"/"{game}" text box on the top screen down a bit so its about 4 pixels above the Text Box under it?
For design wise it would be much pleasing to look at that way for the bgtop.bmp
