### ISSUE TITLE
Issue with Pokemon Games' HTTPS Bypass

### ISSUE THREAD

**Issue by PokeAcer549** [ahezard/NitroHax#3]
https://github.com/Prof9/WfcReplay/issues/24#issuecomment-241481117

I'm using my own codes I generated via WfcReplay v0.7.. :/

**Comment by ApacheThunder** [comment]
NitroHax is not currently compatible with most of the pokemon games. NitroHax doesn't yet init TWL carts correctly yet, so all gen 5 pokemon games do not work. As for gen 4, I don't know which, but I do know of some that don't. Probably all of them.

**Comment by PokeAcer549** [comment]
It's Gen4 games (Pearl + Platinum tested and dont work) - I knew of TWL card's issues.

**Comment by Prof9** [comment]
I've tested with my own retail cart of Platinum US v1.0 using 3DS NitroHax, which uses the same HTTPS bypass code as Platinum EU.

It worked perfectly for me and I could receive a Friend Code and connect to the GTS no problem. However, it stopped working if I soft reset the game (L+R+Start+Select). It looks like that kills the NitroHax code handler in this case (and maybe other cases as well?). Maybe that's what happened here?

**Comment by ShinyMK** [comment]
Yes I can confirm Soft Resetting basically just loads up the game normally, But for me (Pokemon Diamond) it doesnt seem to bypass correctly, Cant get it working.

**Comment by PokeAcer549** [comment]
I updated to the latest NitroHax (0.94), and reinstalled Luma3DS 6.0.1-dev. I've retried with my copy of EU Platinum (UK-specific cart according to other tools online). I loaded up NitroHax and it didnt detect my cart (I had to manually enable HTTPS bypass which is obviously an issue; this didnt occur in the previous version.) I tested WiFi (even though that only connects to a HTTP site - just testing to see if my router was on). I then tried connecting, and I got 20100.
Maybe it does something different on a 'EUR' copy (however unlikely because it's the same ROM)

**Comment by Prof9** [comment]
Leaving the Nintendo WFC settings restarts the game, so that might be triggering a soft reset which kills the NitroHax code handler. Haven't been able to positively confirm this yet though as AltWFC seems to having some issues at the moment.

**Comment by PokeAcer549** [comment]
I can confirm this because Wiimmfi isn't having issues.

**Comment by ShinyMK** [comment]
@PokeAcer549 - I copied your ID from your cheats.xml and it detected my card properly (Couldnt find my cards full ID, Where do I get it?), And im trying to connect to the GTS (Pokemon Diamond) and it still cant connect D:

**Comment by PokeAcer549** [comment]
Your full ID can be gotten by dumping (FBI can dump) and then loading it in R4CCE (at least that's how I do it). Are you ensuring to press A on Pokemon Diamond (region) -> Bypass HTTPS?

**Comment by ShinyMK** [comment]
Yes im full sure, And where can I get R4CCE? Im using Action Replay DSi Code Manager atm

**Comment by PokeAcer549** [comment]
google for it.
Do you have

**Comment by ShinyMK** [comment]
Discord: Shiny#2141

**Comment by ApacheThunder** [comment]
Gen4 pokemon games should definitely work now:

https://github.com/ahezard/NitroHax/releases/tag/0.95.NTR

One user already reported that their game works fine with this build. Any further issues may be related ot the codes being used instead. Gen 5 pokemon games still not fixed as those are TWL carts. TWL carts will need a reworking of the card read code in the cheat engine/bootloader stage of NitroHax.
