### ISSUE TITLE
Pokémon HG EUR not loading - Blackscreen

### ISSUE THREAD

**Issue by cedianoost** [ahezard/NitroHax#5]
Like the title says European version of Pokémon HG just gives a blackscreen, I even tried AP bypass codes, but these didn't work.

**Comment by ApacheThunder** [comment]
I've committed a change that might fix your game. Install the latest release build and let me know if your game works or not:

https://github.com/ahezard/NitroHax/releases/tag/0.95.NTR

**Comment by cedianoost** [comment]
Fixed, I was on the GTS moments ago

**Comment by ApacheThunder** [comment]
Good to hear. I'll go ahead and close this issue then. :D
