### ISSUE TITLE
Game broke outside of Nitrohax?

### ISSUE THREAD

**Issue by ewormPL** [ahezard/NitroHax#6]
Ever since I first used Nitrohax with my Pokémon Soul Silver game, the cartridge icon [went](http://eworm.ovh.org/problemtop.png) [blank](http://eworm.ovh.org/problembot.png) and the game black-screens upon loading the saved game or starting a new game. It works perfectly well _through_ Nitrohax, codes and everything, and it plays okay on my other, non-hacked console, but I'd rather regain the option to play normally.

I tried deleting Nitrohax, I have disabled the twlpatches (especially since they're no longer needed as of 0.96 version), but nothing solves the problem. I'm using a N3DS with Luma3DS + A9LH.

What could be the reason behind this?

**Comment by ApacheThunder** [comment]
Disable the new dev launcher patch from your CFW's config menu. For latest build of luma do this by holding down select on boot to access Luma's config menu. Disable the patch there.

If using dev luma, simply delete/rename twlBg.cxi in luma/sysmodules folder.

Some games get their AP code triggered. This isn't directly related to NitroHax. (only that NitroHax will fix the issue if you have the patch enabled) :P

Latest build of NitroHax no longer requires the patch. you can turn it off now. :D

**Comment by ewormPL** [comment]
You mean the "experimental twlBg patches" option, right? I have already tried disabling that, but it didn't help.

**Comment by ApacheThunder** [comment]
Luma might have a bug where it doesn't really turn it off....Try deleting the config.bin file and reinstalling luma just to be sure.

**Comment by ewormPL** [comment]
It didn't help... I also tried [this solution](https://github.com/Plailect/Guide/wiki/Troubleshooting#twl_broken) from Plailect's guide, but it was no help...

**Comment by ApacheThunder** [comment]
Sounds like maybe an issue with your save file. Not sure what's happening. Still think it's CFW related especially since it works in your other console.

**Comment by ewormPL** [comment]
I tried backing up my save, erasing it and starting the game over, but it black-screened me immediately after the professor speech (meaning when the gameplay begins). So I don't think it's a save file problem...

**Comment by ApacheThunder** [comment]
So that means it has to be CFW related then. Try using a different CFW to see if it's behavior changes.

**Comment by ewormPL** [comment]
Okay, so I tried booting NTR with a CIA launcher and while the icon remained blank, the game launched fine. Then, after rebooting the console, the same happened even without using the NTR. So the main issue has been solved... it's just that the cartridge icon remains blank.

**Comment by ahezard** [comment]
This is not linked to NitroHax, no further paches are needed now.
