### ISSUE TITLE
You keep forgetting to increment the version!

### ISSUE THREAD

**Issue by ImReallyShiny** [ahezard/NitroHax#8]
(The version in-app on the top screen)
On 0.95 it said 0.94 in-app
On 0.96 it said 0.95 in-app

...

**Comment by ApacheThunder** [comment]
0.97 will have the correct value. You could have commented on an existing issue instead of opening a new one. :P

**Comment by ImReallyShiny** [comment]
Commenting on a current issue wouldnt make any sense at all since its not related.
