### ISSUE TITLE
Can we disable the Splash Screen Boot?

### ISSUE THREAD

**Issue by ImReallyShiny** [ahezard/NitroHax#9]
Personally I think its a waste of time looking at it, Is there a way to disable it?

**Comment by ApacheThunder** [comment]
Not currently. You can hold B to disable it in NTR Launcher. However there won't be enough button combos to use for Nitrohax as we are also trying to implement the TWL clock boost option for NTR mode. 

If you want this feature, you will have to convince ahezard to add new options to the UI itself as that's going to be the only way it will ever be skippable.

**Comment by Margen67** [comment]
@ahezard :^)

**Comment by ImReallyShiny** [comment]
Why was it added in the first place? Its basically just a pointless placebo Loading Bar.

**Comment by ApacheThunder** [comment]
It's a matter of opinion and you're in the minority. Either live with the bootsplash or don't use NitroHax

**Comment by ahezard** [comment]
Well button combination is not a good use for this. If I include this it should be via some conf file but I will not integrate any mmi to edit it in NitroHax. And now this boot animation allows you to see if you are in normal ds mode (ds boot animation) or boosted cpu ds mode (dsi animation) so it have some usage.

This issue is not rejected but I consider it really minor.

**Comment by ImReallyShiny** [comment]
Alright :/

**Comment by Margen67** [comment]
Why was this issue closed? He said it wasn't rejected.

**Comment by ApacheThunder** [comment]
Shiny closed it. Ask him. Ahezard has indicated he may add this feature once TWL clock speed option is added to the UI instead of using button combos. But for now it's low priority.

**Comment by ImReallyShiny** [comment]
This is why I closed it, Its pretty much not gonna be a feature. I dont really mind either - Its about 3 ish seconds so who cares :3
